# Generated by Django 5.1.3 on 2024-11-13 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloguinho', '0002_newpost_delete_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='content',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(255)]),
        ),
        migrations.AlterField(
            model_name='newpost',
            name='expires',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='newpost',
            name='image',
            field=models.ImageField(upload_to='static/bloguinho/images/'),
        ),
        migrations.AlterField(
            model_name='newpost',
            name='title',
            field=models.CharField(max_length=127, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
