# Generated by Django 5.1.3 on 2024-11-25 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloguinho', '0003_alter_newpost_content_alter_newpost_expires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='content',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10, 'O conteúdo deve ter pelo menos 10 caracteres.'), django.core.validators.MaxLengthValidator(255, 'O conteúdo deve ter no máximo 255 carateres.')]),
        ),
        migrations.AlterField(
            model_name='newpost',
            name='title',
            field=models.CharField(max_length=127, validators=[django.core.validators.MinLengthValidator(5, 'O título deve ter pelo menos 5 caracteres.')]),
        ),
    ]
